[project]
name = "async-lib"
version = "0.1.0"
description = "A custom implementation of asynchronous operations that is simple, yet fast"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "func-timeout>=4.3.5",
]
